🔹 Level 1: Basic Array Creation
	
	1.	Create a 1D NumPy array with numbers from 10 to 50.
	2.	Create an array of all zeros of size 8.
	3.	Create an array of all ones of shape (3, 3).
	4.	Create an array from 0 to 20 with step 2.
	5.	Create an array of 5 evenly spaced numbers between 1 and 10.

In [2]:
import numpy as np
test_arr = np.array([[10,20,30,40,50]]) #1
print(test_arr)

zeros_arr = np.zeros((8)) #2
print(zeros_arr)

ones_arr = np.ones((3,3)) #3
print(ones_arr)

steps_arry = np.arange(0,20,2) #4
print(steps_arry)

linspace_arr = np.linspace(1,10,5) #5
print(linspace_arr)

[[10 20 30 40 50]]
[0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[ 0  2  4  6  8 10 12 14 16 18]
[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
arr = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])
print(arr[1,1])
print(arr[1])
print(arr[2])
print(arr[1:3,1:3]) #can you tell me how to extract submatrix from the above array?   
arr = np.insert(arr,2,200)
print(arr)


50
[40 50 60]
[70 80 90]
[[50 60]
 [80 90]]
[ 10  20 200  30  40  50  60  70  80  90]


In [29]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a+b)
print(a*b)
print(a*a)
print(a.mean())
print(a.sum())
print(b.sum())

[ 6  8 10 12]
[ 5 12 21 32]
[ 1  4  9 16]
2.5
10
26


In [34]:
arr = np.array([[1,2,3],
                [4,5,6]])
arr2 = np.array([10,20,30])
print(arr+10)
print(arr*2)
print(arr + arr2) #this is called broadcasting. It is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. In this case, arr2 is added to each row of arr, resulting in a new array where each element of arr has been increased by the corresponding element in arr2.

[[11 12 13]
 [14 15 16]]
[[ 2  4  6]
 [ 8 10 12]]
[[11 22 33]
 [14 25 36]]


## How to make array of zeros, ones and full(same number array)

In [ ]:
zeros_array = np.zeros((3, 3))
print(zeros_array)

ones_array = np.ones((2, 3))
print(ones_array)

full_array = np.full((2,3), 2)
print(full_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2 2]
 [2 2 2]]


### Randoms values from 0 to 1.

In [41]:
rand = np.random.random((3,2))
print(rand)

[[0.919631   0.95038813]
 [0.36424174 0.50332002]
 [0.87003439 0.02348535]]


In [51]:
step_arr = np.arange(0,11)
print(step_arr)
print(step_arr[0:3]) #last index is exclusive
print(step_arr.__len__())
print(step_arr[0:10:2]) #step size of 2

[ 0  1  2  3  4  5  6  7  8  9 10]
[0 1 2]
11
[0 2 4 6 8]


## Filtering with Mask

In [54]:
numbers = np.array([1,2,3,4,5,6,7,8,9])
mask = numbers > 4
print(numbers[mask])


[5 6 7 8 9]


## How to add new rows and columes in an exiting np array

In [3]:
fix_arr = np.array([[1,2,3],
                    [4,5,6]])
new_row = np.array([7,8,9])
print(np.vstack((fix_arr, new_row))) #vertical stack
fix_arr2 = np.array([[1],
                     [2],
                     [3]])
new_col = np.array([[4],[5],[6]])
print(np.hstack((fix_arr2, new_col))) #horizontal stack
print(f"this is an new array: {np.hstack((fix_arr2, new_col))}") #f-string

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4]
 [2 5]
 [3 6]]
this is an new array: [[1 4]
 [2 5]
 [3 6]]


In [9]:
test_arr1 = np.array([[5, 10, 15],
                      [20, 25, 30],
                      [35, 40, 45]])
print(test_arr1.shape) #shape of the array
print(test_arr1.ndim)
print(test_arr1.size)#number of elements in the array
print(test_arr1.dtype)

(3, 3)
2
9
int64


## 🔹 Q2: Smart Range Creation
1.	Create numbers from 50 to 100 (step 5).
2.	Create 7 evenly spaced numbers between 0 and 1.
3.	Create a 3×3 matrix of all ones but with integer type.

In [13]:
q_arange = np.arange(50,101,5)
q_spacing = np.linspace(0,1,7)
q_ones = np.ones((3,3),dtype=int)
print(q_arange)
print(q_spacing)
print([q_ones,q_ones.dtype])

[ 50  55  60  65  70  75  80  85  90  95 100]
[0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]
[array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]]), dtype('int64')]


In [20]:
arr = np.array([[11,12,13,14],
                [21,22,23,24],
                [31,32,33,34],
                [41,42,43,44]])
print(arr[1,2])
print(arr[2,:])
print(arr[:,1])
print(arr[1:3,1:3])
arr = np.where(arr == 44 , 999, arr)
print(arr)

23
[31 32 33 34]
[12 22 32 42]
[[22 23]
 [32 33]]
[[ 11  12  13  14]
 [ 21  22  23  24]
 [ 31  32  33  34]
 [ 41  42  43 999]]


In [31]:
a = np.array([2,4,6,8])
b = np.array([1,3,5,7])
print(a+b)
print(a*b)
print(a*a)
print(b.mean())
new_arr = np.concatenate((a,b))
greater = new_arr > 4
print(new_arr[greater])
print(np.where(new_arr > 4 , 100, new_arr))

[ 3  7 11 15]
[ 2 12 30 56]
[ 4 16 36 64]
4.0
[6 8 5 7]
[  2   4 100 100   1   3 100 100]


In [38]:
arr2 = np.array([[1,2,3],
                [4,5,6]])
arr3 = np.array([[10,20,30],
                 [40,50,60]])
print(arr2+5)
print(arr2*[10,20,30])
print(arr2+[100,200,300])
print(f"compatable for broadcasting:{arr2.shape == arr3.shape}")

[[ 6  7  8]
 [ 9 10 11]]
[[ 10  40  90]
 [ 40 100 180]]
[[101 202 303]
 [104 205 306]]
compatable for broadcasting:True


In [45]:
arr = np.array([[10,20,30],
                [40,50,60]])
print(arr.sum(axis=0))
print(arr.mean(axis=1))
print(arr.max())

max_index = np.argmax(arr)# we could also use np.unravel_index to get the row and column index of the maximum value, where(arr == arr.max() also works.
print(max_index)


[50 70 90]
[20. 50.]
60
5


## Reshaping an Array and Transposeing 

In [49]:
arr = np.arange(1,13)
print(arr)
reshaped_arr = arr.reshape((3,4))
print(reshaped_arr)
t_arr = reshaped_arr.T
print(t_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [ ]:
diff_arr = np.array([[1,2,3],[9,8,7],
                     [4,5,6],[10,11,12],
                     [7,8,9],[13,14,15]])
print(diff_arr.ndim)
flat_arr = diff_arr.flatten()
reavel_arr = diff_arr.ravel() #revel returns the same array and flatten returns a copy of the orginal array just flatten the array to 1D.
print(flat_arr)
print(reavel_arr)

2
[ 1  2  3  9  8  7  4  5  6 10 11 12  7  8  9 13 14 15]
[ 1  2  3  9  8  7  4  5  6 10 11 12  7  8  9 13 14 15]


## Use of Mark or Filtering 

In [57]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
con_mask = np.where(arr % 2 == 0, 0, arr)
print(con_mask)

[[1 0 3]
 [0 5 0]
 [7 0 9]]
